### ISSUE TITLE
startup of the service

### ISSUE THREAD

**Issue by jcarres-mdsol** [mdsol/dice_bag#24]
dice_bag is a configuration gem at this moment so it may be out of the scope of this gem. I braindump the idea here anyways.
I would be useful to have a 'rake run'  task to startup the service. We can detect if we are in a rails2, rails3+ or sinatra app to use the correct command. We can also honor some environmental variable like SERVICE_PORT to launch on that port. 

More complex situations where we need to start-up background processes and the like maybe too complex or fragile to support so I am not sure if this is such a good idea. The very least it would create pressure for projects not supported by dice_bag to create their own rake run to be compatible with medidata workflow.

**Comment by asmith-mdsol** [comment]
Good idea. I think it's reasonable to include that in DiceBag for now, as it's really the production facing part of the DiceBag+Kender combination. Together these make up the 12 Factor "rake interface" to an application.

For managing multiple services, we could push people towards foreman (detectable) because it has alternative run modes (runs as its own process, init scripts, upstart script) so it's the correct level of abstraction for us.

**Comment by cross311** [comment]
I realize this enhancement is from a number of years ago.  I personally would NOT like to see this in dice bag.  Foreman is built for this exact thing.  Dice bag in my mind is for taking environment variables making them available for configuration files.  The simplicity of this allows even .Net teams to utilize this gem.

**Comment by jcarres-mdsol** [comment]
We were younger, we thought strangely , I'm closing this
