### ISSUE TITLE
checkmate often has trouble with secret_token.rb.erb ?!?

### ISSUE THREAD

**Issue by mjobin-mdsol** [mdsol/dice_bag#43]
checkmate often has trouble with secret_token.rb.erb ?!?

I dont know what is going on, why this file does not get generated in checkmate?

**Comment by asmith-mdsol** [comment]
Have you commited this template or are you generating it dynamically at configuration time, i.e when you run `rake config:all`? If it's the latter then see #44 because we've decided that you should always commit your configuration templates.

**Comment by mjobin-mdsol** [comment]
this template is in checkmate for a little while already...

```
$ git log config/initializers/secret_token.rb.erb 
commit df87f2ca1623a9b346e506a034455a13790bda58
Author: Andrew Smith <asmith@mdsol.com>
Date:   Thu Oct 11 13:35:53 2012 +0100

    Rename secret_token.rb.example to ...rb.erb

    Switching to a template here allows the secret token to be configured
    from the config rake task.
$ 
```

**Comment by ghost** [comment]
It appears that in at least 0.6.0, the `*.erb` file extension is not supported.  (Probably by design?).  If the file is renamed `config/secret_token.dice` it works.   It's not exactly intuitive that ".dice" is actually an "*.erb" file.

**Comment by asmith-mdsol** [comment]
Yes @chad-medi it's by design, so that we can recursively hit every file in the entire tree and not accidentally clobber other ".erb" files, e.g. in "app/views". Not ideal from a discovery point of view but turned out to be less crazy than the alternatives... although suggestions are always welcome!

In this case you'll want to call it "config/secret_token.rb.dice" with the extra ".rb".

**Comment by mjobin-mdsol** [comment]
solved a long time ago ;)
